spring.application.name=api-gateway
server.port=8091

# Flight Service
spring.cloud.gateway.routes[0].id=flight
spring.cloud.gateway.routes[0].uri=http://flight-service:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/flights/**

# Search Service
spring.cloud.gateway.routes[1].id=search
spring.cloud.gateway.routes[1].uri=http://search-service:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/search/**

# Security Service
spring.cloud.gateway.routes[2].id=security
spring.cloud.gateway.routes[2].uri=http://security-service:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/security/**

# Booking Service
spring.cloud.gateway.routes[3].id=booking
spring.cloud.gateway.routes[3].uri=http://booking-service:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/bookings/**

# Messaging Service
spring.cloud.gateway.routes[4].id=messaging
spring.cloud.gateway.routes[4].uri=http://messaging-service:8086
spring.cloud.gateway.routes[4].predicates[0]=Path=/message/**

# Payment Service
spring.cloud.gateway.routes[5].id=payment
spring.cloud.gateway.routes[5].uri=http://payment-service:8085
spring.cloud.gateway.routes[5].predicates[0]=Path=/pay/**

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Eureka
eureka.client.service-url.defaultZone=http://server:8761/eureka
eureka.instance.prefer-ip-address=true

# JWT
jwt.secret=bXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OTAxMjM0NTY3ODkw