# ======================================
# DOCKER / AZURE PROFILE (NO EUREKA)
# ======================================

spring.application.name=API-Gateway
server.port=8091

# Gateway Routes (Docker service names)
spring.cloud.gateway.routes[10].id=flight-swagger
spring.cloud.gateway.routes[0].uri=http://flight-service:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/flights/**


spring.cloud.gateway.routes[11].id=search-swagger
spring.cloud.gateway.routes[1].uri=http://search-service:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/search/**

spring.cloud.gateway.routes[2].id=security
spring.cloud.gateway.routes[2].uri=http://security-service:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/security/**

spring.cloud.gateway.routes[12].id=booking-swagger
spring.cloud.gateway.routes[3].uri=http://booking-service:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/bookings/**

spring.cloud.gateway.routes[4].id=messaging
spring.cloud.gateway.routes[4].uri=http://messaging-service:8086
spring.cloud.gateway.routes[4].predicates[0]=Path=/message/**

spring.cloud.gateway.routes[5].id=payment
spring.cloud.gateway.routes[5].uri=http://payment-service:8085
spring.cloud.gateway.routes[5].predicates[0]=Path=/pay/**

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# DISABLE EUREKA
# ===============================
eureka.client.enabled=false

# ===============================
# JWT
# ===============================
jwt.secret=bXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OTAxMjM0NTY3ODkw
