spring.application.name=payment-service
server.port=8085

# ===============================
# DATABASE (Docker MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://mysql:3306/FlightBookingSystem
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# STRIPE
# ===============================
stripe.secretKey=${STRIPE_SECRETKEY}
# ===============================
# ? DISABLE EUREKA (Docker mode)
# ===============================
eureka.client.enabled=false
spring.cloud.discovery.enabled=false
spring.cloud.loadbalancer.enabled=false

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.file.name=app.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
